name: superjogodavelha
description: Um Jogo da Velha diferente
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.7.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
  - assets/ic_launcher.png
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  windows: true
  image_path: assets/ic_launcher.png
